version: "3"

services:

    api:
        build:
            context: .
            dockerfile: Dockerfile.api
        restart: always
        container_name: api
        depends_on:
            - mongodb
        ports:
            - 5000:5000
        env_file:
            - ./.env
        command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 5000 --reload"
        volumes:
            - ./:/usr/src/app

    mongodb:
        image: mongo:latest
        container_name: mongodb
        restart: unless-stopped
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
        ports:
            - 27017:27017
        volumes:
          - database-data:/data/db
        
    mongo-express:
        image: mongo-express:latest
        container_name: mongo-express
        restart: unless-stopped
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: password
            ME_CONFIG_MONGODB_SERVER: mongodb


    updater:
        build:
            context: ./updater
            dockerfile: ./Dockerfile.updater
        depends_on:
            - mongodb
        restart: always
        container_name: updater
        env_file:
            - ./.env
        volumes:
            - ./updater:/updater

    # k6:
    #     depends_on:
    #         - api
    #     image: loadimpact/k6
    #     volumes:
    #         - ./tests/load_tests:/load_tests

    redis:
        depends_on:
            - mongodb
        container_name: redis
        image: "redis/redis-stack:latest"
        ports:
            - 6379:6379
            - 8001:8001
        # deploy:
        #     replicas: 1
        #     restart_policy:
        #         condition: on-failure

volumes:
    database-data: